# tasks file for gikeymarcia.sanoid
# https://github.com/jimsalterjrs/sanoid/blob/master/INSTALL.md#debianubuntu
---

- name: Install dependent packages.
  ansible.builtin.apt:
    name:
      - debhelper
      - libcapture-tiny-perl
      - libconfig-inifiles-perl
      - pv
      - lzop
      - mbuffer
      - build-essential
      - git
    state: present

- name: Clone sanoid/syncoid source files from git.
  ansible.builtin.git:
    repo: "https://github.com/jimsalterjrs/sanoid.git"
    dest: /opt/sanoid
    version: "{{ sanoid_version }}"

- name: Install sanoid-suite of tools to PATH
  ansible.builtin.copy:
    src: "/opt/sanoid/{{ item }}"
    dest: "/usr/local/sbin/{{ item }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"
  with_items:
    - sanoid
    - syncoid
    - findoid
    - sleepymutex

- name: Create directory for sanoid configuration
  ansible.builtin.file:
    path: /etc/sanoid
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Install a copy of the default sanoid config (for reference)
  ansible.builtin.copy:
    remote_src: true
    src: /opt/sanoid/sanoid.defaults.conf
    dest: /etc/sanoid/sanoid.defaults.conf
    mode: "0444"

- name: Install systemd unit files
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    mode: "0644"
    owner: root
    group: root
  with_items:
    - sanoid.service
    - sanoid-prune.service

- name: Install systemd timer unit
  ansible.builtin.template:
    src: templates/sanoid.timer.j2
    dest: /etc/systemd/system/sanoid.timer
    mode: "0644"
    owner: root
    group: root

...
# vim: ft=yaml.ansible :
